### ISSUE TITLE
DBSCAN-SWA ignores thread number for blast searches

### ISSUE THREAD

**Issue by alexweisberg** [HIT-ImmunologyLab/DBSCAN-SWA#12]
When I run DBSCAN-SWA using the --thread_num option, it uses 20 threads for the blast/diamond searches regardless of what value I input. In the code (dbscan-swa.py line 386, line 393, line 1523 etc) this 20 thread value is hard coded rather than using the thread number as input.

**Comment by gancao** [comment]
Hi,

The parameter "thread_num" means the number of threads for inputing multiple contigs.  I am sorry to set a fixed value for diamond blastp.  Now, I have updated the code and added a new parameter "diamond_thread_num", representing the thread number of diamond.  You could set it by yourself.

—

**Comment by alexweisberg** [comment]
Hi,

Thank you! I had modified the code on my machine to use the thread_num variable but I will update to the newest version with your fix.
