### ISSUE TITLE
att regions not found even though they exist

### ISSUE THREAD

**Issue by saifasghar** [HIT-ImmunologyLab/DBSCAN-SWA#26]
I'm encountering an issue where certain identified regions from the Phaster analysis of my sequence (available at https://phaster.ca/submissions/NC_019418) are not appearing in the output, despite being detected on the website.

Problem Description:
Upon reviewing the Phaster output for my sequence submission, I've noticed that att regions indicated are not displayed in the generated output.

Steps Taken:

I submitted the sequence using both FASTA and GenBank formats to ensure accuracy.
Reviewed the Phaster output thoroughly to confirm identified regions.
Ensured correct formatting and sequence submission.
Request for Assistance:
Could you please assist in addressing this discrepancy? The identified regions seem to be missing from the output, and I would appreciate guidance on how to resolve this issue.

Thank you for your support.

[Streptococcus phage NJ2.txt](https://github.com/HIT-ImmunologyLab/DBSCAN-SWA/files/14970828/Streptococcus.phage.NJ2.txt)

**Comment by HIT-ImmunologyLab** [comment]
@saifasghar，We apologise for a previous problem with displaying the prediction results for FASTA format sequences. We've resolved the bug, and here are the results for your sequence:
Link to GENBANK format result：
http://www.microbiome-bigdata.com/PHISDetector/index/tools/prophage/result/single_prophage_202431611119113
Link to FASTA format result：
http://www.microbiome-bigdata.com/PHISDetector/index/tools/prophage/result/single_prophage_2024316111197502

**Comment by saifasghar** [comment]
I require the functionality to be implemented within the code to accommodate the analysis of multiple sequences. Would you be able to enhance the code to detect these regions as well? It is imperative that this functionality remains dynamic, ensuring accurate identification of att regions across different sequences.
