### ISSUE TITLE
Issue with dbscan-swa.py script

### ISSUE THREAD

**Issue by traneric** [HIT-ImmunologyLab/DBSCAN-SWA#3]
I'm trying to run the software using the test files and I keep getting this error: 

`File "dbscan-swa.py", line 2773, in <module>
    predict_prophage(strain_id,inputfile_bac,outdir,add_annotation,prefix)
  File "dbscan-swa.py", line 2514, in predict_prophage
    predict_prophage_dbscan_swa(strain_id,bac_fna_file,bac_protein_file,dbscan_region_file,swa_region_file,bac_protein_annotation_file,prophage_outdir,prefix)
  File "dbscan-swa.py", line 1493, in predict_prophage_dbscan_swa
    region_pro_sequence_list,prophage_pro_num = get_protein_to_position_genbank(bac_faa_file,inf['place'],inf['end'],region_faa_file,'DBSCAN-SWA')
TypeError: get_protein_to_position_genbank() missing 1 required positional argument: 'strain_id'`

Any ideas what's happening here?

**Comment by HIT-ImmunologyLab** [comment]
I am very sorry for the error. Now the script has been corrected, you can download the script "dbscan-swa.py" again, the issue can be solved

**Comment by HIT-ImmunologyLab** [comment]
> I'm trying to run the software using the test files and I keep getting this error:
> 
> `File "dbscan-swa.py", line 2773, in <module> predict_prophage(strain_id,inputfile_bac,outdir,add_annotation,prefix) File "dbscan-swa.py", line 2514, in predict_prophage predict_prophage_dbscan_swa(strain_id,bac_fna_file,bac_protein_file,dbscan_region_file,swa_region_file,bac_protein_annotation_file,prophage_outdir,prefix) File "dbscan-swa.py", line 1493, in predict_prophage_dbscan_swa region_pro_sequence_list,prophage_pro_num = get_protein_to_position_genbank(bac_faa_file,inf['place'],inf['end'],region_faa_file,'DBSCAN-SWA') TypeError: get_protein_to_position_genbank() missing 1 required positional argument: 'strain_id'`
> 
> Any ideas what's happening here?

I am very sorry for the error. Now the script has been corrected, you can download the script "dbscan-swa.py" again, the issue can be solved

**Comment by traneric** [comment]
Thank you the script works now
